import Sidebar from '@/components/Sidebar';
import { ThemeProvider } from '@/Providers/theme-provider';
import { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './assets/globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Sistema Financeiro',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                suppressHydrationWarning
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className="flex h-screen">
                        <Sidebar />
                        <div
                            className="flex-1 overflow-auto transition-all duration-300 ease-in-out"
                            style={{ marginLeft: 'var(--sidebar-width, 16rem)' }}
                        >
                            <main className="p-10">{children}</main>
                        </div>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
